# Generated by Django 3.1.1 on 2020-11-23 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('completion', models.SmallIntegerField(default=0)),
                ('progress', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('badge', models.ImageField(default='photos/default_badge.png', null=True, upload_to='photos')),
                ('point', models.PositiveSmallIntegerField(default=0)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('definition', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievement_created_by', to=settings.AUTH_USER_MODEL)),
                ('finisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_finisher', to=settings.AUTH_USER_MODEL)),
                ('task', models.ManyToManyField(to='alcpt.Task')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='achievement',
            field=models.ManyToManyField(to='alcpt.Achievement'),
        ),
    ]
