# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficult',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
