# Generated by Django 3.1.1 on 2020-09-21 23:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='favorite',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='q_correct_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='q_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='photos/default_propic.png', null=True, upload_to='photos'),
        ),
    ]
