# Generated by Django 3.1.1 on 2020-09-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='is_tested',
            field=models.BooleanField(default=False),
        ),
    ]
