# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-12 23:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TesteeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='exam',
            name='group',
        ),
        migrations.AddField(
            model_name='testeelist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alcpt.Exam'),
        ),
        migrations.AddField(
            model_name='testeelist',
            name='testees',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
