# Generated by Django 3.1.1 on 2020-09-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='is_valid',
            new_name='is_favorite',
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='photos/default_propic.png', null=True, upload_to='photos'),
        ),
    ]
