# Generated by Django 3.1.1 on 2020-12-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='key',
            field=models.CharField(max_length=75),
        ),
    ]
