# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-12 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='state',
            field=models.SmallIntegerField(choices=[(0, '暫存'), (1, '審核通過'), (2, '審核未通過'), (3, '等待審核'), (4, '被回報錯誤'), (5, '被回報錯誤，已處理')], default=0),
        ),
    ]
