# Generated by Django 3.2 on 2024-03-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0002_auto_20240304_0101'),
    ]

    # operations = [
    #     migrations.CreateModel(
    #         name='LocationUrl',
    #         fields=[
    #             ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('from_class', models.CharField(default='', max_length=30)),
    #             ('url_name', models.URLField(max_length=50)),
    #         ],
    #     ),
    # ]
