# Generated by Django 3.1.1 on 2020-12-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0002_auto_20201210_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='userachievement',
            name='unlock',
            field=models.BooleanField(default=False),
        ),
    ]
