# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-12 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0002_auto_20200212_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpaper',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
