# Generated by Django 3.2 on 2023-01-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0002_word_exam'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Word_exam',
            new_name='Word_library',
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.PositiveSmallIntegerField(default=112),
        ),
    ]
