# Generated by Django 3.1.1 on 2020-12-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0002_proclamation_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='trophy',
            field=models.ImageField(default='default_trophy/default_trophy.png', upload_to='photos'),
        ),
    ]
