# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-05 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0002_question_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpaper',
            name='is_testpaper',
            field=models.BooleanField(default=1),
        ),
    ]
