# Generated by Django 3.1.1 on 2020-12-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0002_auto_20201214_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='proclamation',
            name='exam_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
