# Generated by Django 3.1.1 on 2020-09-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0002_answersheet_is_tested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
