# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-19 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0003_auto_20191218_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='score',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
