# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-30 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0003_auto_20190430_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
