# Generated by Django 3.1.1 on 2021-01-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0003_achievement_trophy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.PositiveSmallIntegerField(default=110),
        ),
    ]
