# Generated by Django 3.2 on 2023-02-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0003_auto_20230103_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word_library',
            name='translations',
            field=models.CharField(max_length=50),
        ),
    ]
