# Generated by Django 3.2 on 2024-03-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0003_locationurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinestatus',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
    ]
