# Generated by Django 3.1.1 on 2020-09-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0003_auto_20200928_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='score',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
