# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-20 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0004_auto_20191219_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
