# Generated by Django 3.1.1 on 2021-03-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0004_auto_20210125_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='remaining_time',
            field=models.BigIntegerField(default=None),
        ),
    ]
