# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-09 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0004_auto_20190430_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alcpt.Group'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='testpaper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alcpt.TestPaper'),
        ),
    ]
