# Generated by Django 3.2 on 2023-02-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0004_alter_word_library_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word_library',
            name='translations',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='word_library',
            name='words',
            field=models.CharField(max_length=30),
        ),
    ]
