# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-20 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0005_auto_20191220_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='used_freq',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
