# Generated by Django 3.2 on 2024-04-22 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0002_auto_20240308_2324'),
        ('alcpt', '0005_alter_onlinestatus_user'),
    ]

    operations = [
    ]
