# Generated by Django 3.2 on 2023-02-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0005_auto_20230214_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word_library',
            name='words',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
