# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-16 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0005_auto_20190509_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='correcttimes',
            new_name='correct_times',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='usetimes',
            new_name='used_times',
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='questions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.PositiveSmallIntegerField(default=-1),
        ),
    ]
