# Generated by Django 3.1.1 on 2021-03-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0005_exam_remaining_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='modified_times',
        ),
        migrations.AddField(
            model_name='exam',
            name='modified_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
