# Generated by Django 3.1.1 on 2021-03-19 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0006_auto_20210315_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='remaining_time',
        ),
    ]
