# Generated by Django 3.2 on 2023-03-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0006_alter_word_library_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word_library',
            name='words',
            field=models.CharField(max_length=30),
        ),
    ]
