# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-19 03:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0006_auto_20190516_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testpaper',
            name='questions',
        ),
    ]
