# Generated by Django 3.2 on 2024-04-22 01:02

import alcpt.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0006_merge_20240422_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alcpt.answersheet'),
        ),
        migrations.CreateModel(
            name='ScoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.IntegerField(default=2)),
                ('qualified_times', models.PositiveIntegerField(default=0)),
                ('unqualified_times', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_times', alcpt.models.ListField(default=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0])),
                ('testee_num', models.PositiveIntegerField(default=0)),
                ('tested', models.PositiveIntegerField(default=0)),
                ('not_tested_num', models.PositiveIntegerField(default=0)),
                ('testee_score', alcpt.models.ListField(null=True)),
                ('testee_grade', alcpt.models.ListField(null=True)),
                ('qualified_num', models.PositiveIntegerField(default=0)),
                ('unqualified_num', models.PositiveIntegerField(default=0)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='alcpt.exam')),
            ],
        ),
    ]
