# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-30 11:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0007_auto_20191230_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolve_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
