# Generated by Django 3.2 on 2024-04-26 14:34

import alcpt.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0007_auto_20240422_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='testee_grade',
            field=alcpt.models.ListField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='testee_score',
            field=alcpt.models.ListField(blank=True, null=True),
        ),
    ]
