# Generated by Django 3.1.1 on 2021-03-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0007_remove_exam_remaining_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='remaining_time',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
