# Generated by Django 3.2 on 2023-03-14 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0008_alter_word_library_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word_library',
            name='words',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$')]),
        ),
    ]
