# Generated by Django 3.2 on 2023-03-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0009_alter_word_library_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word_library',
            name='translations',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='word_library',
            name='words',
            field=models.TextField(max_length=30),
        ),
    ]
