# Generated by Django 3.1.1 on 2021-12-20 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0010_exam_is_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='forum',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
