# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-04 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0011_user_email_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='resolved_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.PositiveSmallIntegerField(default=109),
        ),
    ]
