# Generated by Django 3.1.1 on 2022-02-21 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0011_auto_20211220_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='forum',
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.PositiveSmallIntegerField(default=111),
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_content', models.TextField()),
                ('data_time', models.DateTimeField(auto_now=True)),
                ('f_creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('f_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alcpt.question')),
            ],
        ),
    ]
