# Generated by Django 3.2 on 2025-10-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0011_auto_20240428_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorerecord',
            name='exam_type',
            field=models.IntegerField(choices=[(1, 'Exam'), (2, 'Practice'), (3, 'Listening'), (4, 'Reading')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.PositiveSmallIntegerField(default=114),
        ),
        migrations.AlterField(
            model_name='word_library',
            name='translations',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='word_library',
            name='words',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
