# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-06 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0012_auto_20200204_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='notification',
            field=models.BooleanField(default=False),
        ),
    ]
