# Generated by Django 3.1.1 on 2022-02-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0012_auto_20220221_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='in_forum',
            field=models.BooleanField(default=False),
        ),
    ]
