# Generated by Django 3.2 on 2025-11-14 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0013_alter_proclamation_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proclamation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcer', to=settings.AUTH_USER_MODEL),
        ),
    ]
