# Generated by Django 3.1.1 on 2022-03-03 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0013_question_in_forum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='data_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
