# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-07 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0013_report_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='notification',
            new_name='staff_notification',
        ),
        migrations.AddField(
            model_name='report',
            name='user_notification',
            field=models.BooleanField(default=False),
        ),
    ]
