# Generated by Django 3.2 on 2025-11-17 13:24

import alcpt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0014_alter_proclamation_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='top_wrong_questions',
            field=alcpt.models.ListField(default=[]),
        ),
        migrations.AddField(
            model_name='examresult',
            name='weakest_category',
            field=models.CharField(default='無', max_length=50),
        ),
    ]
