# Generated by Django 3.1.1 on 2022-03-29 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0015_auto_20220305_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='best_reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='replier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replier', to=settings.AUTH_USER_MODEL),
        ),
    ]
