# Generated by Django 3.2 on 2025-11-17 15:39

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0015_auto_20251117_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='exam',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='alcpt.exam'
            ),
        ),
    ]

