# Generated by Django 3.2 on 2025-11-22 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0016_auto_20251117_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='top_wrong_questions',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='weakest_category',
        ),
    ]
