# Generated by Django 5.2.9 on 2026-06-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0017_auto_20251122_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.PositiveSmallIntegerField(default=115),
        ),
    ]
