# Generated by Django 3.2 on 2023-02-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0017_auto_20220906_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.PositiveSmallIntegerField(default=112),
        ),
    ]
