# Generated by Django 3.2 on 2022-12-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcpt', '0018_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='answord',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
